name: Lint and Build
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: npm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: ESLint
        run: npm lint

      - name: Prettier
        run: npm format:check

      - name: Ensure build succeeds
        run: npm build
